name: Generate contribution snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
                        dist/github-contribution-grid-snake.svg?color_snake=#E4739B&color_dots=#FFF5F7,#FBD3DF,#F0A8BC,#E4739B,#B3325C
                        dist/github-contribution-grid-snake-dark.svg?color_snake=#FFC2D1&color_dots=#241820,#5C2E3E,#A34B6E,#E4739B,#FFC2D1

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
